---
title: "Dissertações dos egressos"
output:
  distill::distill_article
editor_options: 
  chunk_output_type: inline
---



```{r setup, include=FALSE}

library(gsheet)
library(tidyverse)
library(crosstalk)
library(DT)
library(ggthemes)
library(janitor)
library(cowplot)
library(plotly)
library(readxl)
Sys.setlocale("LC_ALL", "pt_BR.UTF-8")

dat0 <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1jKyRWA0YrD6tqW8zayPexHSuXvrKAWnWbl09OG5AHxU/edit?usp=sharing")

dat1 <- dat0 %>% 
  select(Nome, `ano defesa`, orientador, titulo_dissertacao,
         link1, link_dissertacao, link2) %>% 
  unite(link3, link1, link_dissertacao, sep = "") %>% 
  unite(link, link3, link2, sep = "")
sd <- SharedData$new(dat1)


```



```{r echo=FALSE, layout="l-page"}

bscols(
 filter_slider("Ano de defesa", "Restringe aos anos", sd, ~`ano defesa`,
              round = TRUE),

filter_select("orientador", "Orientador", sd, ~orientador,
              multiple = FALSE))

 datatable(sd, 
           escape = FALSE,
           rownames = FALSE,
           extensions = c("Buttons"),
             class = 'table-bordered table-condensed',
           options = list(
              pageLength = 8,
    dom = "Bfrtip", buttons = c("excel")))
           


```
